CREATE TABLE IF NOT EXISTS `Produtos` (
    id VARCHAR(255) PRIMARY KEY UNIQUE,
    `name` VARCHAR(255) NOT NULL,
    price VARCHAR(255) NOT NULL,
    size VARCHAR(255) NOT NULL,
    color VARCHAR(255) NOT NULL,
    tag VARCHAR(255) NOT NULL
);
